train:
  experiment_name: 'semantic_sam'

  # Model
  model:
    sam_name: 'sem_sam'
    params:
      # Fix the a part of parameters in SAM
      fix_img_en: True
      fix_prompt_en: True
      fix_mask_de: False
      ckpt_path: 'sam_ckpt/sam_vit_b_01ec64.pth'
      class_num: 20
      model_type: 'vit_b'    # type should be in [vit_h, vit_b, vit_l, default]

  # Dataset and Dataloader
  dataset:
    name: 'torch_voc_sem'
    params:
      root: '/data/jinziqi/DATASETS/'
      year: '2012'
      image_set: 'train'
    transforms:
      resize: [ [ 1024,1024 ] ]
      to_tensor: [ ]
    target_transforms:
      resize: [ [ 1024,1024 ] ]
      to_tensor: [ ]
    class_num: 20

  # Losses
  losses:
    ce_loss:
      weight: 1.0
      params: ~ # ~ means None type, the initial params of loss could be identified here

# example
#    multi_label_soft_margin:
#      weight: 0.1
#      params: # ~ means None type, the initial params of loss could be identified here
#        reduction: none #

  # Optimizer
  opt_params:
    lr_default: 0.1
    wd_default: 1e-4
    momentum: 0.9
    lr_list: [ 0.1, 0.0001 ]
    group_keys: [ [ '','' ],[ '','' ] ]
    wd_list: [ 0.0, 4e-5 ]
  scheduler_name: 'cosine'
  opt_name: 'sgd'
  # Logger
  use_tensorboard: True
  tensorboard_folder: './experiment/tensorboard'
  log_folder: './experiment/log'
  model_folder: './experiment/model'
  # Others
  max_iter: 1000
  log_iter: 20
  eval_iter: 200
  runner_name: 'sem_runner'
  bs: 4
  num_workers: 1
  drop_last: True

val:
  # Dataset and Dataloader
  dataset:
    name: 'torch_voc_sem'
    params:
      root: '/data/jinziqi/DATASETS/'
      year: '2012'
      image_set: 'train'
    transforms:
      resize: [ [ 1024,1024 ] ]
      to_tensor: [ ]
    target_transforms:
      resize: [ [ 1024,1024 ] ]
      to_tensor: [ ]
    class_num: 20
  bs: 4
  num_workers: 1
  drop_last: True


test:
  need_test: True
