train:
  experiment_name: 'semantic_sam'
  dataset_name: 'voc_sem'
  bs: 16
  num_workers: 8
  drop_last: True
  loss_names: [ 'ce_loss','multi_label_soft_margin' ]
  loss_weight: [ 0.1, 0.1 ]
  sam_name: 'sem_sam'
  opt_params:
    lr_default: 0.1
    wd_default: 1e-4
    momentum: 0.9
    lr_list: [ 0.1, 0.0001 ]
    group_keys: [ [ '','' ],[ '','' ] ]
    wd_list: [ 0.0, 4e-5 ]
  scheduler_name: 'cosine'
  opt_name: 'sgd'
  fix_img_encoder: True
  fix_prompt_encoder: True
  fix_mask_decoder: True
  max_iter: 100
  log_iter: 10
  eval_iter: 20
  log_folder: './log'
  model_folder: './model'
  transfomrs: [ '','' ]
test:
  need_test: True
