train:
  # Fix the a part of parameters in SAM
  fix_img_encoder: True
  fix_prompt_encoder: True
  fix_mask_decoder: False
  # Model
  experiment_name: 'semantic_sam'
  sam_name: 'sem_sam'
  ckpt_path: 'sam_ckpt/sam_vit_h_4b8939.pth'
  # Dataset and Dataloader
  dataset_name: 'voc_sem'
  bs: 16
  num_workers: 8
  drop_last: True
  transfomrs: [ 'to_tensor','resize' ]
  # Losses
  loss_names: [ 'ce_loss','multi_label_soft_margin' ]
  loss_weight: [ 0.1, 0.1 ]
  # Optimizer
  opt_params:
    lr_default: 0.1
    wd_default: 1e-4
    momentum: 0.9
    lr_list: [ 0.1, 0.0001 ]
    group_keys: [ [ '','' ],[ '','' ] ]
    wd_list: [ 0.0, 4e-5 ]
  scheduler_name: 'cosine'
  opt_name: 'sgd'
  max_iter: 100
  log_iter: 10
  eval_iter: 20
  runner_name: 'sem_runner'
  # Logger
  log_folder: './log'
  model_folder: './model'


val:
  # Dataset and Dataloader
  dataset_name: 'voc_sem'
  bs: 16
  num_workers: 8
  drop_last: True
  transfomrs: [ 'to_tensor','resize' ]

test:
  need_test: True
