train:
  # Fix the a part of parameters in SAM
  fix_img_encoder: True
  fix_prompt_encoder: True
  fix_mask_decoder: False
  # Model
  experiment_name: 'semantic_sam'
  sam_name: 'sem_sam'
  ckpt_path: 'sam_ckpt/sam_vit_b_01ec64.pth'
  # Dataset and Dataloader
  dataset:
    name: 'torch_voc_sem'
    params:
      root: '/data/jinziqi/DATASETS/'
      year: '2012'
      image_set: 'train'
    transforms:
      resize: [ [ 1024,1024 ] ]
      to_tensor: [ ]
    target_transforms:
      resize: [ [ 1024,1024 ] ]
      to_tensor: [ ]
    class_num: 20
  bs: 1
  num_workers: 1
  drop_last: True
  # Losses
  losses:
    ce_loss:
      weight: 0.1
      params: ~ # ~ means None type, the initial params of loss could be identified here

# example
#    multi_label_soft_margin:
#      weight: 0.1
#      params: # ~ means None type, the initial params of loss could be identified here
#        reduction: none #

  # Optimizer
  opt_params:
    lr_default: 0.1
    wd_default: 1e-4
    momentum: 0.9
    lr_list: [ 0.1, 0.0001 ]
    group_keys: [ [ '','' ],[ '','' ] ]
    wd_list: [ 0.0, 4e-5 ]
  scheduler_name: 'cosine'
  opt_name: 'sgd'
  max_iter: 100
  log_iter: 10
  eval_iter: 20
  runner_name: 'sem_runner'
  # Logger
  use_tensorboard: False
  log_folder: './log'
  model_folder: './model'


val:
  # Dataset and Dataloader
  dataset:
    name: 'torch_voc_sem'
    params:
      root: '/data/jinziqi/DATASETS/'
      year: '2012'
      image_set: 'val'
    transforms:
      resize: [ [ 512,512 ] ]
      to_tensor: [ ]
    target_transforms:
      resize: [ [ 512,512 ] ]
      to_tensor: [ ]
  bs: 16
  num_workers: 8
  drop_last: True


test:
  need_test: True
